### ISSUE TITLE
Unable to add custom data to the constructor

### ISSUE THREAD

**Issue by priteshbonde** [PDFTron/webviewer-angular-sample#13]
I am trying to set custom data to the Webviewer contructor as in this [document ](https://www.pdftron.com/documentation/web/guides/config-files/#passing-custom-data).
Below is my code for initialisation.
` 
WebViewer({
      path: '../lib',
      initialDoc: '../files/webviewer-demo-annotated.pdf',
      custom: {startPage: 2},
    }, this.viewer.nativeElement).then(instance => {
      console.log(instance);
      this.wvInstance = instance;
      const { Annotations } = instance;      // now you can access APIs through this.webviewer.getInstance()
      instance.openElements(['notesPanel']);
      instance.enableElements(['bookmarksPanel', 'bookmarksPanelButton']);
    });`

I get error ` Object literal may only specify known properties, and 'custom' does not exist in type 'WebViewerOptions'` 
Am i missing something?

**Comment by mparizeau-pdftron** [comment]
Sorry we missed responding to this earlier. If you want to pass it to be accessible in your config file you'll want to stringify the value as it shows in the guide that you linked, for example `JSON.stringify({ startPage: 2})`

It looks like the `custom` option isn't in our documentation which is why it isn't showing up in the TypeScript file. This stackoverflow post shows how you could ignore that TypeScript error https://stackoverflow.com/a/31816062
