### ISSUE TITLE
How to create button on top right

### ISSUE THREAD

**Issue by Elikill58** [PDFTron/webviewer-angular-sample#18]
Hi,

I would like to know how to add a new button in the showed area (on top right) with specific action.

![image](https://user-images.githubusercontent.com/17381066/114668726-57e3b100-9d01-11eb-9984-48192b7896d4.png)

**Comment by mparizeau-pdftron** [comment]
Here are some examples of customizing the header https://www.pdftron.com/documentation/web/guides/customizing-header/#examples. You may want to use the insertBefore API to insert before the search button https://www.pdftron.com/api/web/Header.html#insertBefore

Since this isn't directly related to the angular sample I would recommend adding follow up questions to our community forum at https://community.pdftron.com/ as you'll likely be able to get a faster answer.

**Comment by Elikill58** [comment]
Hi,
Thanks you, Yes I find the community !
I will try !
